/dxl_driver:
  ros__parameters:
    driver:
      frequency: 1.0

    servos:
      ids: [1] # Servo IDs
      operating_modes: [4] # Driver operating mode, [4 is position control]
      homing_modes: [0] # Homing mode, [0 is no homing]
      directions: [1] # Direction of rotation for each servo [-1, 1]
      max_speeds: [0.1] # Maximum allowable speed in rad/s
      gear_ratios: [3.0] # Gear ratio between servo horn and output shaft
      min_angles: [-1.57] # Minimum angle limit in rad (if both set to zero, no limits are applied)
      max_angles: [1.57] # Maximum angle limit in rad (if both set to zero, no limits are applied)
